// Central route registry — single source of truth for all page IDs, slugs, titles, descriptions.
// Imported by App.tsx, SEOLayout.tsx. Mirrored in scripts/prerender.mjs (Node.js can't import TS).

export type Page =
  | 'home' | 'generator' | 'finder' | 'templates' | 'scripts' | 'batch'
  | 'privacy' | 'terms' | 'cookies' | 'about' | 'contact' | 'blog' | 'free-tools'
  | 'pricing' | 'account' | 'features' | 'use-cases'
  | 'guide' | 'guide-instagram' | 'guide-youtube' | 'guide-comparison'
  | 'guide-tiktok-comment-generator' | 'guide-tiktok-comment-picker' | 'guide-tiktok-giveaway-picker'
  | 'hashtag-generator' | 'font-generator' | 'caption-generator' | 'engagement-calculator'
  | 'video-ideas-generator' | 'hook-generator' | 'comment-reply-generator' | 'bio-generator' | 'cta-generator'
  | 'blog-tiktok-username-ideas'
  | 'blog-tiktok-giveaway' | 'blog-ugc-content' | 'blog-tiktok-algorithm' | 'blog-tiktok-views';

export const SLUG_TO_PAGE: Record<string, Page> = {
  '/': 'home',
  '/app': 'generator',
  '/question-finder': 'finder',
  '/templates': 'templates',
  '/script-generator': 'scripts',
  '/batch-generator': 'batch',
  '/privacy': 'privacy',
  '/terms': 'terms',
  '/cookies': 'cookies',
  '/about': 'about',
  '/contact': 'contact',
  '/blog': 'blog',
  '/free-tools': 'free-tools',
  '/pricing': 'pricing',
  '/account': 'account',
  '/features': 'features',
  '/use-cases': 'use-cases',
  '/tiktok-username-ideas': 'blog-tiktok-username-ideas',
  '/tiktok-giveaway-guide': 'blog-tiktok-giveaway',
  '/what-is-ugc-content': 'blog-ugc-content',
  '/tiktok-algorithm-guide': 'blog-tiktok-algorithm',
  '/how-to-get-more-views-tiktok': 'blog-tiktok-views',
  '/how-to-add-comment-sticker-tiktok': 'guide',
  '/instagram-comment-sticker-generator': 'guide-instagram',
  '/youtube-comment-sticker-generator': 'guide-youtube',
  '/tiktok-comment-generator-alternatives': 'guide-comparison',
  '/tiktok-comment-generator': 'guide-tiktok-comment-generator',
  '/tiktok-comment-picker': 'guide-tiktok-comment-picker',
  '/tiktok-giveaway-picker': 'guide-tiktok-giveaway-picker',
  '/hashtag-generator': 'hashtag-generator',
  '/tiktok-font-generator': 'font-generator',
  '/caption-generator': 'caption-generator',
  '/engagement-rate-calculator': 'engagement-calculator',
  '/tiktok-video-ideas-generator': 'video-ideas-generator',
  '/tiktok-hook-generator': 'hook-generator',
  '/comment-reply-generator': 'comment-reply-generator',
  '/tiktok-bio-generator': 'bio-generator',
  '/cta-generator': 'cta-generator',
};

export const PAGE_TO_SLUG: Record<Page, string> = Object.fromEntries(
  Object.entries(SLUG_TO_PAGE).map(([slug, page]) => [page, slug])
) as Record<Page, string>;

export const PAGE_TITLES: Record<Page, string> = {
  home: 'Free TikTok Comment Mockup Generator for UGC Ads | CommentSticker',
  generator: 'Comment Mockup Generator — Create UGC Comment Overlays Free',
  finder: 'Find Viral TikTok Questions | CommentSticker',
  templates: 'UGC Comment Templates Library | CommentSticker',
  scripts: 'AI UGC Script Generator | CommentSticker',
  batch: 'Batch Comment Sticker Generator | CommentSticker',
  privacy: 'Privacy Policy | CommentSticker',
  terms: 'Terms of Service | CommentSticker',
  cookies: 'Cookie Policy | CommentSticker',
  about: 'About CommentSticker — Free UGC Tools for Creators',
  contact: 'Contact Us | CommentSticker',
  blog: 'Blog & Guides for TikTok Creators | CommentSticker',
  'free-tools': 'Free Social Media Tools for Creators | CommentSticker',
  pricing: 'Pricing — CommentSticker Pro | Unlimited Exports & All Platforms',
  account: 'My Account | CommentSticker',
  features: 'Features — Everything CommentSticker Can Do | Free Tools for Creators',
  'use-cases': 'Use Cases — How Creators Use CommentSticker for UGC & Ads',
  'blog-tiktok-username-ideas': '200+ TikTok Username Ideas for 2026 — Name Ideas for Girls, Boys & More',
  'blog-tiktok-giveaway': 'How to Run a TikTok Giveaway in 2026: Complete Step-by-Step Guide',
  'blog-ugc-content': 'What is UGC Content? The Complete 2026 Guide for Creators and Brands',
  'blog-tiktok-algorithm': 'How the TikTok Algorithm Works in 2026: Complete For You Page Guide',
  'blog-tiktok-views': 'How to Get More Views on TikTok in 2026: 15 Proven Strategies',
  guide: 'How to Add Comment Stickers on TikTok (Complete 2026 Guide)',
  'guide-instagram': 'Free Instagram Comment Sticker Generator for Reels',
  'guide-youtube': 'Free YouTube Comment Sticker Generator for Shorts',
  'guide-comparison': 'Best TikTok Comment Generator in 2026: Top Alternatives',
  'guide-tiktok-comment-generator': 'Free TikTok Comment Mockup Generator for UGC Ad Creatives',
  'guide-tiktok-comment-picker': 'TikTok Comment Picker — Free Random Winner Tool',
  'guide-tiktok-giveaway-picker': 'TikTok Giveaway Picker — Free Random Winner Selector',
  'hashtag-generator': 'Free Hashtag Generator for TikTok & Instagram (2026)',
  'font-generator': 'TikTok Font Generator — Copy & Paste Fonts for Bio & Captions',
  'caption-generator': 'Free Caption Generator — TikTok, Instagram & LinkedIn',
  'engagement-calculator': 'Engagement Rate Calculator — Free Tool for All Platforms (2026)',
  'video-ideas-generator': 'Free TikTok Video Ideas Generator — 500+ Ideas by Niche (2026)',
  'hook-generator': 'Free TikTok Hook Generator — High-Retention Hooks for Every Niche',
  'comment-reply-generator': 'Free TikTok Comment Reply Generator — Replies for Any Comment',
  'bio-generator': 'Free TikTok Bio Generator — Optimized Bios by Niche & Vibe (2026)',
  'cta-generator': 'Free CTA Generator for TikTok, Instagram, YouTube & LinkedIn',
};

export const PAGE_DESCRIPTIONS: Record<Page, string> = {
  home: 'CommentSticker is a free comment mockup generator for UGC creators and advertisers. Build pixel-perfect TikTok, Instagram, YouTube & LinkedIn comment overlays for video ad creatives — transparent PNG, no watermark.',
  generator: 'Create pixel-perfect comment mockup overlays for TikTok, Instagram, YouTube and more. Designed for UGC ad creatives, content demos and creator tutorials. Download as transparent PNG. Free, no login, no watermark.',
  finder: 'Discover the most viral questions and comments for your niche. Use them as hooks in your TikTok UGC ads.',
  templates: 'Browse 100+ proven UGC comment templates for TikTok, Instagram and YouTube ads. Free to use.',
  scripts: 'Generate high-converting UGC video scripts based on your comment hooks. Free AI script generator.',
  batch: 'Generate and download multiple comment stickers at once. Batch export PNG for TikTok, Instagram, YouTube. Free, no watermark.',
  privacy: 'Privacy Policy for CommentSticker — how we collect, use, and protect your data.',
  terms: 'Terms of Service for CommentSticker.',
  cookies: 'Cookie Policy for CommentSticker — how we use cookies, localStorage, Google AdSense and analytics, plus how to opt out.',
  about: 'Learn about CommentSticker — the free UGC creative tool built for creators, marketers, and brands.',
  contact: 'Get in touch with the CommentSticker team.',
  blog: 'Guides, tutorials and strategies for TikTok UGC creators. Learn how to create comment stickers, run giveaways, and grow your audience.',
  'free-tools': 'All free social media tools in one place — hashtag generator, font generator, caption generator, engagement rate calculator, comment picker and giveaway picker.',
  pricing: 'Get CommentSticker Pro — unlimited exports, all 9 platforms, batch generator, no watermark, no ads. $9/month or $69/year.',
  account: 'Manage your CommentSticker subscription, billing, and account settings.',
  features: 'Explore all CommentSticker features — 9 platforms, transparent PNG export, batch generator, comment picker, 15+ free tools for TikTok, Instagram and YouTube creators.',
  'use-cases': 'See how creators, brands and agencies use CommentSticker — UGC ads, TikTok content, brand social proof, giveaways, reels and more.',
  'blog-tiktok-username-ideas': '200+ TikTok username ideas for 2026 — cute, aesthetic, funny, dark academia, Y2K and personal-brand names for girls and boys. Find a unique TikTok name with your name.',
  'blog-tiktok-giveaway': 'Complete guide to running a successful TikTok giveaway in 2026 — rules, promotion strategy, how to pick a random winner, and mistakes to avoid.',
  'blog-ugc-content': 'What is UGC content? Learn what User Generated Content means, why brands pay for it, and how to start as a UGC creator in 2026 — no following required.',
  'blog-tiktok-algorithm': 'How the TikTok algorithm works in 2026 — ranking signals, For You Page distribution model, and 10 actionable strategies to get more views.',
  'blog-tiktok-views': 'Get more views on TikTok with these 15 proven strategies — hook optimization, completion rate, hashtags, posting times, and audience retention tips.',
  guide: 'Learn how to add a comment sticker on a TikTok video natively and using a free generator. Ultimate 2026 guide.',
  'guide-instagram': 'Create a perfect Instagram comment sticker for Reels. Free generator, transparent PNG, no watermark.',
  'guide-youtube': 'Create a YouTube comment sticker for Shorts. Free generator, 3x resolution, transparent PNG.',
  'guide-comparison': 'Comparison of the best free TikTok comment generator tools in 2026. Find the best TokComment alternative.',
  'guide-tiktok-comment-generator': 'Use a free TikTok comment mockup generator to create pixel-perfect comment overlays as transparent PNGs for UGC ad creatives and content demos.',
  'guide-tiktok-comment-picker': 'Pick a random winner from TikTok comments for free. Best TikTok comment picker tools compared for 2026.',
  'guide-tiktok-giveaway-picker': 'Run a fair TikTok giveaway and pick a random winner from comments or followers. Free tools compared.',
  'hashtag-generator': 'Generate the best TikTok, Instagram and YouTube hashtags for your niche. Free hashtag generator — copy and paste instantly, no sign-up.',
  'font-generator': 'Generate stylish fonts for TikTok bio and captions. Bold, italic, script, Fraktur and 13 more Unicode font styles. Copy and paste free.',
  'caption-generator': 'Generate engaging social media captions for TikTok, Instagram, LinkedIn and YouTube. Free caption generator with hashtag suggestions.',
  'engagement-calculator': 'Calculate your social media engagement rate for TikTok, Instagram, YouTube, Twitter, LinkedIn and Facebook. Free tool with industry benchmarks.',
  'video-ideas-generator': 'Generate 500+ TikTok video ideas by niche and format. Free TikTok video ideas generator — tutorials, POVs, challenges, reactions and more. No sign-up.',
  'hook-generator': 'Generate high-retention TikTok hooks for your niche. Free hook generator with 8 hook types — question, secret, mistake, POV, number, contrast, hot take, storytime.',
  'comment-reply-generator': 'Generate perfect TikTok comment replies for compliments, questions, criticism, and haters. Free reply generator with 4 tones. Copy and paste instantly.',
  'bio-generator': 'Generate optimized TikTok bios for your niche and vibe. Free TikTok bio generator with character counter — funny, inspiring, professional, bold and more.',
  'cta-generator': 'Generate high-converting calls-to-action for TikTok, Instagram, YouTube and LinkedIn. Free CTA generator — follow, comment, save, share, link in bio and more.',
};

// Schema.org structured data — injected as <script type="application/ld+json"> per page
export const PAGE_SCHEMAS: Partial<Record<Page, object>> = {
  home: {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'CommentSticker',
    url: 'https://commentsticker.com/',
    description: 'Free TikTok comment mockup generator — create pixel-perfect transparent PNG comment overlays for UGC ad creatives, content demos and tutorials.',
    potentialAction: {
      '@type': 'SearchAction',
      target: 'https://commentsticker.com/app',
      'query-input': 'required name=search_term_string',
    },
  },
  generator: {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'CommentSticker Generator',
    applicationCategory: 'DesignApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Free tool to generate pixel-perfect comment mockup overlays for TikTok, Instagram, YouTube, LinkedIn, and more. Designed for UGC ad creatives, content demos and tutorials. Transparent PNG, no watermark.',
    url: 'https://commentsticker.com/app/',
    featureList: 'TikTok comments, Instagram comments, YouTube comments, LinkedIn comments, PNG export, JPEG export, Batch generator',
  },
  batch: {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'CommentSticker Batch Generator',
    applicationCategory: 'DesignApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Generate and download up to 10 comment stickers at once for TikTok, Instagram, YouTube and more. Free batch PNG/JPEG export, no watermark.',
    url: 'https://commentsticker.com/batch-generator/',
  },
  finder: {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'CommentSticker Question Finder',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Discover viral TikTok questions and comment hooks for your niche. Free tool for UGC creators and ad marketers.',
    url: 'https://commentsticker.com/question-finder/',
  },
  templates: {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'CommentSticker Templates Library',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Browse 100+ proven UGC comment templates for TikTok, Instagram and YouTube ads. Copy and use for free.',
    url: 'https://commentsticker.com/templates/',
  },
  scripts: {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'CommentSticker AI Script Generator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Generate high-converting UGC video scripts from comment hooks. Free AI script generator for TikTok and Instagram.',
    url: 'https://commentsticker.com/script-generator/',
  },
  guide: {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Add a Comment Sticker on TikTok',
    description: 'Step-by-step guide to adding comment stickers on TikTok natively or using a free generator.',
    step: [
      { '@type': 'HowToStep', name: 'Open TikTok and create a video', text: 'Tap the + button in TikTok to record or upload your video.' },
      { '@type': 'HowToStep', name: 'Tap the Stickers icon', text: 'After recording, tap the Stickers icon (smiley face) in the editor toolbar.' },
      { '@type': 'HowToStep', name: 'Select a comment to react to', text: 'Scroll and select the comment from your video that you want to feature as a sticker.' },
      { '@type': 'HowToStep', name: 'Position and post', text: 'Drag the comment sticker to your desired position and post your video.' },
    ],
  },
  'guide-instagram': {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Create an Instagram Comment Sticker for Reels',
    description: 'Generate a pixel-perfect Instagram comment sticker as a transparent PNG for your Reels.',
    step: [
      { '@type': 'HowToStep', name: 'Open CommentSticker Generator', text: 'Go to commentsticker.com/app and select Instagram.' },
      { '@type': 'HowToStep', name: 'Customize the comment', text: 'Enter username, comment text, and set the likes count.' },
      { '@type': 'HowToStep', name: 'Download the PNG', text: 'Click Export PNG to download a transparent PNG at 3x resolution.' },
      { '@type': 'HowToStep', name: 'Add to your Reel', text: 'Import the PNG in CapCut or Premiere and overlay on your video.' },
    ],
  },
  'guide-youtube': {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Create a YouTube Comment Sticker for Shorts',
    description: 'Generate a YouTube comment sticker as a transparent PNG for YouTube Shorts.',
    step: [
      { '@type': 'HowToStep', name: 'Open CommentSticker Generator', text: 'Go to commentsticker.com/app and select YouTube.' },
      { '@type': 'HowToStep', name: 'Customize the comment', text: 'Enter channel name, comment text, and likes count.' },
      { '@type': 'HowToStep', name: 'Export as PNG', text: 'Download the transparent PNG at 3x resolution for crisp display in Shorts.' },
      { '@type': 'HowToStep', name: 'Add to your Short', text: 'Overlay the PNG in your video editor at the top of the frame.' },
    ],
  },
  'guide-tiktok-comment-generator': {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Create a TikTok Comment Mockup for UGC Ads',
    description: 'Build a pixel-perfect TikTok comment mockup overlay as a transparent PNG for UGC ad creatives and content demos.',
    step: [
      { '@type': 'HowToStep', name: 'Go to the generator', text: 'Open commentsticker.com/app and select TikTok.' },
      { '@type': 'HowToStep', name: 'Configure the mockup overlay', text: 'Set username, avatar, comment text, likes, and timestamp to match your UGC ad creative or content demo.' },
      { '@type': 'HowToStep', name: 'Export as transparent PNG', text: 'Click Export PNG. The file downloads at 3x pixel ratio with transparent background.' },
    ],
  },
  'guide-tiktok-comment-picker': {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Pick a Random TikTok Comment Winner',
    description: 'Use a free TikTok comment picker to select a random winner for your giveaway.',
    step: [
      { '@type': 'HowToStep', name: 'Copy your TikTok video comments', text: 'Export or copy all comments from your giveaway video.' },
      { '@type': 'HowToStep', name: 'Paste into the picker tool', text: 'Paste comments into the free CommentSticker picker (one per line).' },
      { '@type': 'HowToStep', name: 'Click Pick a Winner', text: 'Hit the button. The tool randomly selects one commenter as the winner.' },
    ],
  },
  'guide-tiktok-giveaway-picker': {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Pick a Random TikTok Giveaway Winner',
    description: 'Run a fair TikTok giveaway and pick a random winner from comments or followers. Free tools compared.',
    step: [
      { '@type': 'HowToStep', name: 'Collect giveaway entries', text: 'Copy all comments from your TikTok giveaway post or gather follower entries.' },
      { '@type': 'HowToStep', name: 'Paste into a picker tool', text: 'Use a free TikTok giveaway picker — paste entries one per line into the tool.' },
      { '@type': 'HowToStep', name: 'Pick a random winner', text: 'Click the pick button. The tool randomly selects one eligible commenter as the winner.' },
    ],
  },
  'guide-comparison': {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'Best TikTok Comment Generator in 2026: Top Alternatives Compared',
    description: 'Comparison of the best free TikTok comment generator tools in 2026. Find the best TokComment alternative.',
    url: 'https://commentsticker.com/tiktok-comment-generator-alternatives/',
    publisher: { '@type': 'Organization', name: 'CommentSticker', url: 'https://commentsticker.com/' },
  },
  'hashtag-generator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'TikTok Hashtag Generator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Generate the best TikTok, Instagram and YouTube hashtags for your niche. Free hashtag generator with 12 niches and viral/growth/niche tiers.',
    url: 'https://commentsticker.com/hashtag-generator/',
  },
  'font-generator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'TikTok Font Generator',
    applicationCategory: 'DesignApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Generate 13 stylish Unicode font styles for TikTok bio, captions and usernames. Bold, italic, script, cursive, Fraktur and more. Free copy & paste.',
    url: 'https://commentsticker.com/tiktok-font-generator/',
  },
  'caption-generator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'Social Media Caption Generator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Free caption generator for TikTok, Instagram, LinkedIn and YouTube. Choose your platform, vibe, and topic — get 4 ready-to-post captions instantly.',
    url: 'https://commentsticker.com/caption-generator/',
  },
  'engagement-calculator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'Social Media Engagement Rate Calculator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Calculate your engagement rate for TikTok, Instagram, YouTube, Twitter, LinkedIn and Facebook. Free tool with industry benchmarks and improvement tips.',
    url: 'https://commentsticker.com/engagement-rate-calculator/',
  },
  'free-tools': {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: 'Free Social Media Tools',
    url: 'https://commentsticker.com/free-tools/',
    description: 'All free social media tools by CommentSticker — hashtag generator, font generator, caption generator, engagement calculator, comment picker and giveaway picker.',
    publisher: { '@type': 'Organization', name: 'CommentSticker', url: 'https://commentsticker.com/' },
  },
  'video-ideas-generator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'TikTok Video Ideas Generator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Free TikTok video ideas generator — 500+ ideas across 12 niches and 8 formats. Tutorials, POVs, challenges, reactions, comparisons and more. No sign-up.',
    url: 'https://commentsticker.com/tiktok-video-ideas-generator/',
  },
  'hook-generator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'TikTok Hook Generator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Free TikTok hook generator — 8 hook types (question, secret, mistake, POV, number, contrast, hot take, storytime) across 8 niches. Copy and paste instantly.',
    url: 'https://commentsticker.com/tiktok-hook-generator/',
  },
  'comment-reply-generator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'TikTok Comment Reply Generator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Free TikTok comment reply generator — perfect replies for compliments, questions, criticism, haters, collab requests and more. 4 tone options. Copy and paste.',
    url: 'https://commentsticker.com/comment-reply-generator/',
  },
  'bio-generator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'TikTok Bio Generator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Free TikTok bio generator — 5 optimized bios per niche and vibe combination. Includes character counter for TikTok\'s 80-character limit. Copy and paste instantly.',
    url: 'https://commentsticker.com/tiktok-bio-generator/',
  },
  'cta-generator': {
    '@context': 'https://schema.org',
    '@type': ['SoftwareApplication', 'WebApplication'],
    name: 'Social Media CTA Generator',
    applicationCategory: 'MarketingApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Free CTA generator for TikTok, Instagram, YouTube and LinkedIn. 8 goal types — follow, comment, save, share, link in bio, duet, collab, profile. Copy and paste.',
    url: 'https://commentsticker.com/cta-generator/',
  },
  'blog-tiktok-giveaway': {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'How to Run a TikTok Giveaway in 2026: Complete Step-by-Step Guide',
    description: 'Complete guide to running a successful TikTok giveaway — rules, strategy, winner selection, and best practices.',
    url: 'https://commentsticker.com/tiktok-giveaway-guide/',
    datePublished: '2026-04-14',
    dateModified: '2026-04-14',
    publisher: { '@type': 'Organization', name: 'CommentSticker', url: 'https://commentsticker.com/' },
  },
  'blog-ugc-content': {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'What is UGC Content? The Complete 2026 Guide for Creators and Brands',
    description: 'Everything you need to know about UGC content — definition, types, why brands pay for it, and how to become a UGC creator.',
    url: 'https://commentsticker.com/what-is-ugc-content/',
    datePublished: '2026-04-14',
    dateModified: '2026-04-14',
    publisher: { '@type': 'Organization', name: 'CommentSticker', url: 'https://commentsticker.com/' },
  },
  'blog-tiktok-algorithm': {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'How the TikTok Algorithm Works in 2026: Complete For You Page Guide',
    description: 'A complete breakdown of the TikTok algorithm, FYP ranking signals, distribution model, and 10 actionable strategies.',
    url: 'https://commentsticker.com/tiktok-algorithm-guide/',
    datePublished: '2026-04-14',
    dateModified: '2026-04-14',
    publisher: { '@type': 'Organization', name: 'CommentSticker', url: 'https://commentsticker.com/' },
  },
  'blog-tiktok-views': {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'How to Get More Views on TikTok in 2026: 15 Proven Strategies',
    description: '15 data-backed strategies to get more TikTok views — hook optimization, completion rate, hashtags, posting times, and audience retention.',
    url: 'https://commentsticker.com/how-to-get-more-views-tiktok/',
    datePublished: '2026-04-14',
    dateModified: '2026-04-14',
    publisher: { '@type': 'Organization', name: 'CommentSticker', url: 'https://commentsticker.com/' },
  },
  'blog-tiktok-username-ideas': {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: '200+ TikTok Username Ideas for 2026 — Name Ideas for Girls, Boys & More',
    description: '200+ TikTok username ideas for 2026 — cute, aesthetic, funny, dark academia, Y2K and personal-brand names. Find a unique TikTok name with your name.',
    url: 'https://commentsticker.com/tiktok-username-ideas/',
    datePublished: '2026-04-04',
    dateModified: '2026-04-04',
    publisher: { '@type': 'Organization', name: 'CommentSticker', url: 'https://commentsticker.com/' },
  },
  blog: {
    '@context': 'https://schema.org',
    '@type': 'Blog',
    name: 'CommentSticker Blog & Guides',
    url: 'https://commentsticker.com/blog/',
    description: 'Guides, tutorials and strategies for TikTok UGC creators. Learn how to create comment stickers, run giveaways, and grow your audience.',
    publisher: {
      '@type': 'Organization',
      name: 'CommentSticker',
      url: 'https://commentsticker.com/',
    },
  },
};
